/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/products': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					page?: string;
					limit?: string;
					search?: string;
					store?: 'LIDL' | 'BILLA' | 'COOP' | 'BIEDRONKA' | 'KAUFLAND' | 'TESCO';
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success: get products */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProductListResponse'];
					};
				};
				/** @description Chyba validácie (vstupných dát) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Chyba na strane servera */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/availablestores': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Success: get available stores */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': ('LIDL' | 'BILLA' | 'COOP' | 'BIEDRONKA' | 'KAUFLAND' | 'TESCO')[];
					};
				};
				/** @description Server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/list/add': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: {
				content: {
					'application/json': {
						/** @example 123 */
						productId: number;
						/**
						 * @default shoppingList
						 * @example shoppingList
						 * @enum {string}
						 */
						listType?: 'shoppingList' | 'customList' | 'aiList';
					};
				};
			};
			responses: {
				/** @description Položka pridaná do zoznamu */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AddListResponse'];
					};
				};
				/** @description Neautorizovany */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Produkt nenajdeny */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Položka už v zozname existuje */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Chyba servera */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/list/all': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Item list uzivatelsky zoznam. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							ok: boolean;
							data: Record<string, never>[];
						};
					};
				};
				/** @description Neautorizovany uzivatel */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Chyba servera */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/list/remove/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Produkt bol úspešne vymazaný zo zoznamu. */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							/** @enum {boolean} */
							ok: true;
							message: string;
						};
					};
				};
				/** @description Neautorizovany uzivatel */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Produkt nebol najdeny. */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description Chyba servera pri mazaní produktu zo zoznamu. */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ProductListResponse: {
			ok: boolean;
			data: components['schemas']['Product'][];
			meta: components['schemas']['PaginationMeta'];
		};
		Product: {
			id: number;
			leafletId: string;
			productName: string;
			searchName: string;
			price: string;
			originalPrice: string | null;
			/** @enum {string} */
			storeName: 'LIDL' | 'BILLA' | 'COOP' | 'BIEDRONKA' | 'KAUFLAND' | 'TESCO';
			isAction: boolean;
			cardRequired: boolean;
			discountPercentage: string | null;
			category: string | null;
			validFrom: string;
			validUntil: string;
			unit: string | null;
			amount: string | null;
			unitPrice: string | null;
			page: number;
			box_2d?: unknown;
			linkToPhoto: string | null;
			linkToAction: string | null;
			moreInfo: string | null;
			createdAt: string;
		};
		PaginationMeta: {
			total: number;
			page: number;
			limit: number;
			totalPages: number;
		};
		ErrorResponse: {
			/** @enum {boolean} */
			ok: false;
			error: string;
			/** @example Pole "page" musí byť číslo */
			details?: unknown;
		};
		AddListResponse: {
			ok: boolean;
			data?: components['schemas']['UserListItem'];
			message?: string;
		};
		UserListItem: {
			id: string;
			savedName: string;
			/** @example 10.99 */
			savedPrice?: number;
			/** @enum {string} */
			savedStore: 'LIDL' | 'BILLA' | 'COOP' | 'BIEDRONKA' | 'KAUFLAND' | 'TESCO';
			isCompleted: boolean;
			/** Format: date-time */
			createdAt: string;
			shoppingListId: string;
			productPriceId: number | null;
			productPrice?: number | null;
			shoppingList?: number | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
